### ISSUE TITLE
imoniang.com的依赖拉不下来

### ISSUE THREAD

**Issue by DavisLinger** [moniang/chat#1]
`imoniang.com/chat/sql`这种依赖拉不下来导致缺少无法完成编译

**Comment by moniang** [comment]
恩。。其实就是本项目里的sql文件夹里面的东西

**Comment by moniang** [comment]
建议你
`go build`
打包，然后运行打包出来的文件

**Comment by DavisLinger** [comment]
`go build`会因为没有依赖无法编译，建议改为将`imoniang.com/chat/sql`改为`github.com/moniang/chat`，这样就能够找到你sql包
