### ISSUE TITLE
大佬网页端可以参考这个聊天室

### ISSUE THREAD

**Issue by Yakumo-Yukari** [moniang/chat#1]
参考网站：https://233.nie.im/

要不要也像这个聊天室一样加入消息提示音 和  语音播放消息内容呢

**Comment by JensonYang20** [comment]
好啊
那怎样就可以干翻qq了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yakumo-Yukari"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 上午9:40
收件人:&nbsp;"moniang/chat"<chat@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[moniang/chat] 大佬网页端可以参考这个聊天室 (#1)





 
参考网站：https://233.nie.im/
 
要不要也像这个聊天室一样加入消息提示音 和  语音播放消息内容呢

**Comment by Yakumo-Yukari** [comment]
> 好啊 那怎样就可以干翻qq了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Yakumo-Yukari"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月18日(星期三) 上午9:40 收件人:&nbsp;"moniang/chat"<chat@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[moniang/chat] 大佬网页端可以参考这个聊天室 (#1) 参考网站：https://233.nie.im/ 要不要也像这个聊天室一样加入消息提示音 和 语音播放消息内容呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以可以 期待下！

**Comment by Yakumo-Yukari** [comment]
> 好啊 那怎样就可以干翻qq了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Yakumo-Yukari"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月18日(星期三) 上午9:40 收件人:&nbsp;"moniang/chat"<chat@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[moniang/chat] 大佬网页端可以参考这个聊天室 (#1) 参考网站：https://233.nie.im/ 要不要也像这个聊天室一样加入消息提示音 和 语音播放消息内容呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![批注 2020-03-18 130555](https://user-images.githubusercontent.com/12076232/76927313-9863d600-6919-11ea-85cd-3de62a2f313e.png)

他这个登录后就可以设置这些功能
